### ISSUE TITLE
what is different from fabric-sdk-py

### ISSUE THREAD

**Issue by nobody4t** [yeasy/hyperledger-py#13]
Hi Bao hua, 

As I can see the difference is that this repos is out of date, right? But the sdk repo is updated regularly.
The three branches in this repo are not updated since last Sep. Does that mean this repo is 
dead now? If I want to learn something about the hyperledger python sdk, should I just go for fabric-sdk-py repo?

**Comment by yeasy** [comment]
hi, wandy.
the repo (only support fabric v0.6) has been migrated to the fabric-sdk-py (which will support fabric 1.0 and more new features)
